# Project information
site_name: Le Bac - à - sable 2.0
# site_url: ""
site_author: D'Hans-Trapp
site_description: >-
  Où l’on parle principalement d’écriture de fiction numérique avec Twine, de photos, souvent enrichies, et de publication en ligne avec Jekyll

# Copyright
copyright: D'Hans-Trapp fecit &copy; 2024 

plugins:
  - git-revision-date-localized:
      fallback_to_build_date: true
      timezone: Europe/Paris
      type: custom
      custom_format: "Article mis à jour le %d/%m/%Y"
  - search

    

markdown_extensions:
  - footnotes
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.blocks.caption
  - admonition

extra_css:
  - stylesheets/extra.css
  
theme:
  name: material
  language: fr
  logo: assets/images/logo.png
  custom_dir: overrides
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    primary: grey
    accent: red

  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

  features:
    - navigation.footer
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - navigation.path
    - navigation.sections
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - content.footnote.tooltips
    - content.tooltips
  

  # Additional configuration
extra:
  social:
    - icon: fontawesome/brands/github
      link: http://github.com/marathon67
    - icon: fontawesome/brands/mastodon
      link: https://mastouille.fr/@hans_trapp
    - icon: fontawesome/brands/facebook 
      link: https://www.facebook.com/pierre.kessler.771
    - icon: fontawesome/brands/deviantart
      link: https://www.deviantart.com/hans-trapp
 # generator: false

nav:
  - 'À propos':  
    - 'Accueil': index.md
    - 'Présention de MkDocs': mkdocs.md
    - 'Exemples de typographie': specimen.md
  - 'Photographie':
      - 'En général':
        - 'Critique bien conduite': critique-bien-conduite.md
        - 'Images zoomables': images-zoomables.md
      - 'Polarisation croisée':
          - 'Introduction': polarisation-croisee.md
          - 'Découper et positionner les filtres': polarisation-croisee1.md
          

